# Generated by Django 4.0.4 on 2022-05-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('qr_code', models.ImageField(blank=True, upload_to='Attendance')),
            ],
            options={
                'verbose_name_plural': 'Attendance QR',
            },
        ),
        migrations.CreateModel(
            name='Attendance_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('private_id', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('year', models.CharField(max_length=250)),
                ('note', models.CharField(blank=True, max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Attendance List',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('qr_code', models.ImageField(blank=True, upload_to='Leave')),
            ],
            options={
                'verbose_name_plural': 'Leave QR',
            },
        ),
        migrations.CreateModel(
            name='Leave_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('private_id', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('year', models.CharField(max_length=250)),
                ('note', models.CharField(blank=True, max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Leave List',
            },
        ),
    ]
