# Generated by Django 4.0.4 on 2022-05-19 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_attendance_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('Class', models.CharField(max_length=250)),
                ('create_in', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.attendance')),
            ],
            options={
                'verbose_name_plural': 'Attendance List',
            },
        ),
    ]
