# Generated by Django 4.0.4 on 2022-05-19 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_attendance_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance_List',
        ),
    ]
