# Generated by Django 4.0.4 on 2022-05-20 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_attendance_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_list',
            name='ip',
        ),
    ]
