# Generated by Django 4.0.4 on 2022-05-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_attendance_list_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_list',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='attendance_list',
            name='login_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
