# Generated by Django 4.0.4 on 2022-05-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_attendance_list_ip_attendance_list_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_list',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
