# Generated by Django 4.0.4 on 2022-05-20 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_attendance_list_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_list',
            old_name='login_id',
            new_name='loginid',
        ),
        migrations.RenameField(
            model_name='attendance_list',
            old_name='qr_code',
            new_name='qrcode',
        ),
    ]
