# Generated by Django 4.0.4 on 2022-05-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_dr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_list',
            name='qrcode',
        ),
        migrations.RemoveField(
            model_name='attendance_list',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Attendance_List',
        ),
    ]
