# Generated by Django 4.0.4 on 2022-05-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_attendance_list_qrcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('date', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('qr_code', models.ImageField(blank=True, upload_to='Attendance')),
                ('dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dr')),
            ],
            options={
                'verbose_name_plural': 'Attendance QR',
            },
        ),
    ]
