# Generated by Django 4.0.4 on 2022-05-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_attendance_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='name',
            new_name='subject_name',
        ),
    ]
