# Generated by Django 4.0.4 on 2022-05-21 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_leave_list_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_list',
            name='qrcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.leave'),
        ),
    ]
